/*Направете функця add(), която събира две точки.*/
#include<stdio.h>

struct point{
    int x;
    int y;
};

struct point add(struct point first, struct point second);

int main(){
    struct point a = {3,4};
    struct point b = {7,8};
    struct point c = add(a, b); 

    printf("The coordinates of point A(%d, %d)\n", a.x, a.y);
    printf("The coordinates of point B(%d, %d)\n", b.x, b.y);
    printf("The coordinates of the new point generated by the sum of pointA and pointB is C(%d, %d)\n", c.x, c.y);

    return 0;
}

struct point add(struct point first, struct point second){
    struct point newPoint;
    newPoint.x = first.x + second.x;
    newPoint.y = first.y + second.y;

    return newPoint;
}